import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";
import { SITE_NAME } from "../constants/seo.constants";
import { Provider } from "./providers";
import { Toaster } from "sonner";

const zen = Roboto({
  subsets: ["cyrillic", "latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
  variable: "--font-zen",
  style: ["normal"],
});

export const metadata: Metadata = {
  title: {
    default: SITE_NAME,
    template: `%s | ${SITE_NAME}`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={zen.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
